### ISSUE TITLE
找不到 RCTRootView.h

### ISSUE THREAD

**Issue by hmhm7442** [Bob1993/React-Native-Gank#1]
Gank/ios/ReactNativeGank/AppDelegate.m:12:9: 'RCTRootView.h' file not found

我是直接clone 的你项目运行的

**Comment by poberwong** [comment]
1. 在根目录下执行： npm install 来安装所有的依赖包
2. 点击ios下的 ReactNativeGank.xcodeproj 文件执行  
   **_注意：前提是你能跑通正常的Demo喔～么么哒**_

**Comment by hmhm7442** [comment]
thx
