### ISSUE TITLE
启动app报错

### ISSUE THREAD

**Issue by LeonXtp** [Bob1993/React-Native-Gank#10]
undefined is not an object( evaluating 'screenPhysicalPixels.width')

**Comment by XepherJin** [comment]
我也遇到这个问题了

**Comment by poberwong** [comment]
嗯，我也是刚刚发现，正在解决中......

**Comment by poberwong** [comment]
@LeonJavaAndroid  @RetroPoktan  应该是只有Android有这个问题，iOS暂时还没有

**Comment by poberwong** [comment]
重新生成android项目工程就可以搞定。
因为我们把react-native从0.19升级到0.20之后，如果不同时升级Android项目工程，会导致一些问题

### 总结如下：
- 我们升级Native项目模块，主要是为了升级Native工程对react-native依赖库的升级以及相关代码的更新
- 经常碰到升级之后出现这个找不到，那个无法识别，就是native层对接react-native（如MainActivity）的Api接口发生了变化。
- 如果只升级React－Native，建议重新组织下载`node_modules`所有的依赖库，因为一些Rn依赖的库也需要升级....否则红屏等着你....

### 解决方案：
- `react-native android`  仅仅重新生成Android模块
- `react-native upgrade`  ios、Android都重新生成
  以上如果存在自己修改Native层代码的情况，最好进行备份

### 参考：
- [Github](https://github.com/facebook/react-native/issues/5963)
- [react-native官方文档](http://facebook.github.io/react-native/docs/upgrading.html#content)

### 结束语：
- 留图不留种，菊花万人捅
- 升级只升Rn，坑多踩不完

**Comment by jiangqqlmj** [comment]
嘎嘎 +1
