### ISSUE TITLE
Something Error

### ISSUE THREAD

**Issue by akerdi** [Bob1993/React-Native-Gank#11]
一进页面就出现Something Error，gank的source是不是变了呀？？前几天还能显示的列

**Comment by poberwong** [comment]
哈哈，红条是我刚做的一个类似于Android的SnackBar的自定义控件。因为我之前组织数据API的时候，由于Gank.io 所提供的before关键字只能获取日期之前的，所以我直接给日期＋1，这样今天就包含在before所能获取数据范围之内了。这样就导致每个月月底的时候，会出现1-32，2-30，3-32 这样的API数据接口，这显然是有问题的。马上根据新的API进行修复哈～

**Comment by akerdi** [comment]
好的，，谢啦，，哈哈

**Comment by poberwong** [comment]
@shaohung001 已经修复啦～快去试试看

**Comment by akerdi** [comment]
大哥，，，他还是这样，，嘎嘎，，，我对着您的写的，您自己的，，都是这样，，，嘎嘎，，，😢我写着好好的，快第一遍写完了，，打算再写个3遍的，，居然木有用列，，嗷嗷

**Comment by akerdi** [comment]
现在还是SomeThing Error

**Comment by poberwong** [comment]
我这边已经可以了，你看看是哪部分数据没获取到，打一下日志看看

**Comment by akerdi** [comment]
好的，，晚上我去看看，白天稍忙一点，，嘿嘿，，我看那个request类有点吃力，，断点有些打不过，，我尽量试试，，，嘿嘿

**Comment by poberwong** [comment]
嗯，Request不是个类，只能算是一个对象。的确，网络请求都在那里。主要是Promise的使用有点压力

**Comment by akerdi** [comment]
可以了，没问题了，，嘿嘿，，，我再写写本地版本的，，就转过来重写啦，，嘿嘿
