### ISSUE TITLE
react-native-navigationba  -找不到

### ISSUE THREAD

**Issue by jorry** [Bob1993/React-Native-Gank#13]
需要在哪里配置么？

**Comment by poberwong** [comment]
你执行`npm install` 了嘛？

**Comment by jorry** [comment]
执行了，其他页面的JS能正常执行，是不是targetSdkVersion问题/
我看了下，不是这个问题
还有其他可能的问题么

**Comment by poberwong** [comment]
不应该啊，react-native-navigtionbar 是我写的一个库啊
