### ISSUE TITLE
Application ReactNativeGank hasnot been registered...

### ISSUE THREAD

**Issue by XTaoWang** [Bob1993/React-Native-Gank#15]
![wechat_1463711406](https://cloud.githubusercontent.com/assets/10386006/15415550/e1626df0-1e75-11e6-9576-75d0de6d2be7.jpeg)

**Comment by poberwong** [comment]
哈哈，发现我们居然是群友......  一般，发生这种问题大都不是代码的问题，因为注册这个如果真的出问题了，肯定是代码漏掉了，显然这不可能。... 所以可能如下：
1. 8081 端口被其他rn工程占用了
2. npm install安装项目依赖库了吗？
3. 本地8081端口的packager服务没启动成功？

**Comment by XTaoWang** [comment]
哈，图片出卖了我，嗯 ，才开始研究 Rn
