### ISSUE TITLE
loadMore时出错

### ISSUE THREAD

**Issue by FrankyLee-dev** [Bob1993/React-Native-Gank#20]
undefined is not an object(evaluating 'contentData.results.福利[0]')

**Comment by poberwong** [comment]
可能是API出问题了.... 这个项目是我初学时写的，建议移驾 [mdcc-client](https://github.com/Bob1993/mdcc-client) 这个项目，优点如下：
- 使用redux架构，数据流清晰
- 代码更加简洁，组件之间耦合度合理
- 异步请求使用redux的middleware处理，更加优雅

**Comment by FrankyLee-dev** [comment]
thanks!
