### ISSUE TITLE
运行时候的问题

### ISSUE THREAD

**Issue by lpslpsl** [Bob1993/React-Native-Gank#21]
不知道是不是我手机原因。我一运行就跑到设置里面的应用管理去了（魅族）。（好像我自己新的项目运行也会自动跳到应用列表，然后按返回才会到app界面），然后我按了返回就回到桌面了、完全没有走启动的感觉。。

**Comment by poberwong** [comment]
RN项目在Android上需要 弹出悬浮窗权限，因此你需要手动去开启.... 开了之后应该就可以运行了

**Comment by lpslpsl** [comment]
恩恩。开了权限之后果然可以进去了。虽然还是红的。万分感谢

**Comment by poberwong** [comment]
红的那就要继续调试了

**Comment by lpslpsl** [comment]
想问下。后面正确连接手机了。然后运行就闪退了，能有办法看到报错信息么

**Comment by poberwong** [comment]
Android 的话，可以在终端使用  adb logcat查看日志，或者使用IDE 如 Android Studio 之类的工具查看日志信息
