### ISSUE TITLE
请问一下react-native-navigationbar  这个在哪里可以找到？

### ISSUE THREAD

**Issue by xiaolongonly** [Bob1993/React-Native-Gank#23]
我这边现在报错是Unknown named module:'react-native-navigationbar'

**Comment by xiaolongonly** [comment]
ok，我将 react-native改成了 react-native 成功运行

**Comment by xiaolongonly** [comment]
= = 还是有问题~   这个NavigationBar是自定义组件吗

**Comment by xiaolongonly** [comment]
![qq 20161219142104](https://cloud.githubusercontent.com/assets/12853050/21303019/796af612-c5f6-11e6-9b83-30d24dea193a.png)
这里有个像依赖库一样的东西

**Comment by xiaolongonly** [comment]
找到解决方案
cd 到项目根路径

3使用命令： npm install react-native-navigationbar–save

**Comment by poberwong** [comment]
文件记录里已经有了的，是不需要 --save 的
