### ISSUE TITLE
首先，多谢你的贡献，下面有个问题，ios跑不起来，请看一下

### ISSUE THREAD

**Issue by michaelmou** [Bob1993/React-Native-Gank#3]
- react-native bundle --entry-file index.ios.js --platform ios --dev true --bundle-output /Users/Michael/Library/Developer/Xcode/DerivedData/ReactNativeGank-gdlgyuyapoaikxfstgokwtmhuicm/Build/Products/Debug-iphoneos/ReactNativeGank.app/main.jsbundle --assets-dest /Users/Michael/Library/Developer/Xcode/DerivedData/ReactNativeGank-gdlgyuyapoaikxfstgokwtmhuicm/Build/Products/Debug-iphoneos/ReactNativeGank.app
  ../node_modules/react-native/packager/react-native-xcode.sh: line 49: react-native: command not found
  Command /bin/sh failed with exit code 127

**Comment by poberwong** [comment]
看到最后一句： `react-native: command not found` ，  
1. 请问你的React－Native环境配好了吗？
2. 正常的Demo能跑起来吗？

**Comment by poberwong** [comment]
我看你这个命令是用来打iOS包的，建议使用Xcode， debug或者release包都很简单
