### ISSUE TITLE
 第一次运行失败，提示Unhandled JS Exception

### ISSUE THREAD

**Issue by yuncat** [Bob1993/React-Native-Gank#5]
Unhandled JS Exception: Application ReactNativeGank has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.

**Comment by poberwong** [comment]
试着重新开启一下node服务（在项目根目录下运行`npm start` 或者完全关闭ReactNative项目以及本地服务器，然后重新运行项目）
