### ISSUE TITLE
React-Native开发需要看哪些书籍，求推荐

### ISSUE THREAD

**Issue by fhefh2015** [Bob1993/React-Native-Gank#6]
目前做前端和iOS开发，开个issues，问哈需要看哪些书籍
O(∩_∩)O谢谢

**Comment by poberwong** [comment]
老实说，国内的相关书籍的确很缺乏。即使有（我知道的一到两本），出书的速度也是很难跟得上facebook官网的更新的，而且我看过部分的目录，就是对facebook官网文档的翻译，毫无营养。所以，Github以及facebook官方文档还有npm以及国外朋友写的博客就显得尤为重要，我在下一个评论里给你加上几个我常用的资料，你也可以平时多关注我star的一些项目，那都会是不错的信息

**Comment by poberwong** [comment]
## Github:
- [react-native学习资料大全](https://github.com/ele828/react-native-guide)
- [face-book github](https://github.com/facebook/react-native)

## 文档教程:
- [react-native中文文档](http://reactnative.cn)
- [react-native官方文档(推荐)](http://reactnative.com)

＃第三方平台:
- [稀土掘金](http://gold.xitu.io)
- [江清清的Rn专栏](http://www.lcode.org/react-native)
- [_我的博客(刚买的域名，hexo暂时处于瘫痪状态，最近应该会放到简书上，我不会写一些过于基础的文章，毕竟基础来源于文档，却无法高于文档)_](http://poberwong.com)
- [我的简书](http://www.jianshu.com/users/5f2821bda896/latest_articles)
