### ISSUE TITLE
Could not download stetho.jar

### ISSUE THREAD

**Issue by maoruibin** [Bob1993/React-Native-Gank#7]
执行 react-native run-android 报以下错误 

`A problem occurred configuring project ':app'.

> Could not download stetho.jar (com.facebook.stetho:stetho:1.2.0)
> Could not get resource 'https://jcenter.bintray.com/com/facebook/stetho/stetho/1.2.0/stetho-1.2.0.jar'.
>       > Could not GET 'https://jcenter.bintray.com/com/facebook/stetho/stetho/1.2.0/stetho-1.2.0.jar'.
>          > Connection to https://akamai.bintray.com refused`

下载不到 stetho.jar 其实我是已经翻墙了的，不知你遇到过这个问题没

**Comment by maoruibin** [comment]
好吧，后来重试了几次，又可以正常下载了  _—_

**Comment by poberwong** [comment]
给两个解决方案吧
- 使用iOS来跑程序，相对省点事（iOS的开发环境要比Android好很多，GFW fuck 之）
- 这个属于Native层的问题，因为我在原生代码里添加了translucent statusbar的原因，最好不要手动重新生成android工程。如果你会写translucent statusbar（现在已经在ReactNative层支持修改Android的statusbar了）或者暂时不在乎status美观问题的话，可以先删除android工程，然后使用`react-native android` 来重新生成android项目
