### ISSUE TITLE
apk 安装 就停在splash界面了

### ISSUE THREAD

**Issue by TigerChain** [Bob1993/React-Native-Gank#9]
apk 安装 就停在splash界面了，使用android5.0系统

**Comment by poberwong** [comment]
apk 安装？你装的是签名包吗？

**Comment by cbyniiaii** [comment]
从fir.im下载安装的，就停在splash界面了，使用android5.0系统

**Comment by poberwong** [comment]
splash ? 什么意思？ 当前fir上边的应该是稳定的,不过有个bug就是在每个月月末的时候，会进不去app，目前已经在master上修复了

**Comment by TigerChain** [comment]
好了，就是停在loading界面了，现在好了

**Comment by poberwong** [comment]
哈哈，今天是月末，应该加载不出来东西的...建议去pull一下master分支的代码，然后可以调试或者打包看看
